apiVersion: v1
kind: Service
metadata:
  name: pyspark-notebook
spec:
  ports:
  - port: 8889
    name: pyspark-notebook
    targetPort: 8889
  - port: 4040
    name: webui0
    targetPort: 4040
  - port: 4041
    name: webui1
    targetPort: 4041
  selector:
    app: pyspark-notebook
  type: LoadBalancer


