apiVersion: v1
kind: Pod
metadata:
  name: notebook
  labels:
    app : notebook
spec:
  containers:
  - name: notebook
    image: arkaisho/minimal-notebook
    ports:
      - name: web
        containerPort: 8888
        protocol: TCP
